# ...existing code...
# Remove the following import:
# from .financial import (FinancialRecordListView, FinancialRecordCreateView,
#                       FinancialRecordUpdateView, FinancialRecordDeleteView)
# ...existing code...